DROP TABLE IF EXISTS PERSON;

CREATE TABLE "PERSON"(
    "ID" INTEGER NOT NULL,
    "FIRST_NAME" VARCHAR(255) NOT NULL,
    "LAST_NAME" VARCHAR(255) NOT NULL,
    "ADDRESS_ID" INTEGER DEFAULT NULL
);

DROP TABLE IF EXISTS ADDRESS;

CREATE TABLE "ADDRESS"(
    "ID" INTEGER NOT NULL,
    "CITY" VARCHAR(255),
    "POSTAL_CODE" INTEGER NOT NULL,
    "STATE" VARCHAR(255),
    "STREET" VARCHAR(255)
);